language: node_js
node_js:
- '7.8'
env:
  - CXX=g++-4.8
addons:
  - ssh_known_hosts: $DEPLOY_HOST
  - apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
