language: node_js
node_js:
- '7'
env:
  - CXX=g++-4.8
addons:
  - ssh_known_hosts: $DEPLOY_HOST
  - apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
 - KEY_ENC=.travis/sandbox.pem.enc
 - KEY=.travis/sandbox.pem
 - openssl aes-256-cbc -K $encrypted_c6c040438739_key -iv $encrypted_c6c040438739_iv -in $KEY_ENC -out $KEY -d
 - rm $KEY_ENC
 - chmod 600 $KEY
 - ssh-add $KEY
 - git remote add deploy $DEPLOY_REMOTE
 - git checkout -b deploy-branch
 - git push -f deploy deploy-branch
