language: node_js
node_js:
- '7'
after_success:
- set -x
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_c6c040438739_key -iv $encrypted_c6c040438739_iv -in .travis/sandbox.pem.enc -out .travis/sandbox.pem -d
- rm .travis/sandbox.pem.enc
- chmod 600 .travis/sandbox.pem
- mv .travis/sandbox.pem ~/.ssh/id_rsa
- git remote add deploy server@174.138.73.162:/home/server/surveyscribe.git
- git config user.name "Travis CI"
- git push -f deploy master
