language: node_js
cache:
  directories:
  - node_modules # NPM packages
node_js:
  - '7'

addons:
  ssh_known_hosts: 174.138.73.162

before_deploy:
- openssl aes-256-cbc -K $encrypted_1a5f07d3a46d_key -iv $encrypted_1a5f07d3a46d_iv -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy-key.pem
- ssh-add deploy-key.pem
- git remote add deploy ssh://server@174.138.73.162/home/server/surveyscribe.git

deploy:
  provider: script
  skip_cleanup: true
  script: git push -f deploy master
  on:
    branch: master
