language: node_js
node_js:
- '7.8'
addons:
  ssh_known_hosts: 174.138.73.162
before_deploy:
  - chmod +x ./deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
