language: node_js
node_js:
- '7'
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key.pem
- ssh-add .travis/deploy_key.pem
- git remote add deploy ssh://server@174.138.73.162/home/server/surveyscribe.git
- git push deploy
before_install:
- openssl aes-256-cbc -K $encrypted_1a5f07d3a46d_key -iv $encrypted_1a5f07d3a46d_iv
  -in deploy_key.enc -out deploy_key -d
