language: node_js
node_js:
- '7'
after_success:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_1a5f07d3a46d_key -iv $encrypted_1a5f07d3a46d_iv -in .travis/id_deploy.enc -out .travis/id_deploy -d
- chmod 600 .travis/id_deploy
- ssh-add .travis/id_deploy
- git remote add deploy ssh://server@174.138.73.162/home/server/surveyscribe.git
- git push -f deploy master
