language: node_js

node_js:
  - '7'

addons:
  ssh_known_hosts: <deploy-host>

before_deploy:
- openssl aes-256-cbc -K $encrypted_6a5cf90fd664_key -iv $encrypted_6a5cf90fd664_iv -in deploy-key.enc -out /tmp/deploy-key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy-key
- ssh-add /tmp/deploy-key
- git remote add deploy ssh://server@174.138.73.162/home/server/surveyscribe.git

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
