language: node_js
node_js:
- '7.8'
env:
  - CXX=g++-4.8
addons:
  - ssh_known_hosts: $DEPLOY_HOST
  - apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - git clone https://github.com/ScribeTech/Sandbox.git clone
  - mv clone .
  - chmod u+x .travis/deploy.sh
deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
