language: node_js
node_js:
- '7'
addons:
  ssh_known_hosts: 174.138.73.162
after_success:
  - eval "$(ssh-agent -s)"
  - KEY_ENC=.travis/sandbox.pem.enc
  - KEY=.travis/sandbox.pem
  - openssl aes-256-cbc -K $encrypted_c6c040438739_key -iv $encrypted_c6c040438739_iv -in $KEY_ENC -out $KEY -d
  - rm $KEY_ENC
  - chmod 600 $KEY
  - mv $KEY_ENC ~/.ssh/id_rsa
  - git remote add deploy server@174.138.73.162:/home/server/sandbox.git
  - git push -f deploy master
